base/urls.py
from django.urls import path
from base import views

# URL configuration for base
# Add the app_name ("base") to set the app namespace
app_name = "base"

urlpatterns = [
    path('', views.home, name='home'),
    path('impressum/', views.imprint, name='imprint'),
    path('datenschutzrichtlinien/', views.privacy_policy, name='privacy-policy'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render
from base.provider import Provider

def home(request):
    return render(request, 'base/home.html', {})

def imprint(request):
    return render(request, 'base/imprint.html', {'provider' : Provider,})

def privacy_policy(request):
    return render(request, 'base/privacy_policy.html', {'provider' : Provider,})

base/templates/base/base.html
<!doctype html>
<html lang="de" class="h-100">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{% block meta_description %}{% endblock %}">
        <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body class="d-flex flex-column h-100">
        <header class="fixed-top">
            <!-- Main navigation bar -->
            {% include 'base/main_navigation_ bar.html' %}
        </header>
        <!-- Page content -->
        <main class="flex-shrink-0" style="padding-top: 60px;">
            <div class="container">       
                {% block content %}{% endblock %}
            </div>
        </main>
        <footer class="footer mt-auto py-3 bg-light">
            <div class="container text-center">              
                <ul class="nav justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'base:imprint' %}">
                            Impressum
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'base:privacy-policy' %}">
                            Datenschutzrichtlinien
                        </a>
                    </li>
                </ul>
                <small>
                    &copy; 2024 Your Company
                </small>
            </div>
        </footer>
        <!-- Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

base/templates/base/home.html
{% extends 'base/base.html' %}

{% block title %}
Das ist meine Startseite
{% endblock %}

{% block meta_description %}
Das ist meine Beschreibug der Startseite
{% endblock %}

{% block meta_keywords %}
Startseite, Webanwendung
{% endblock %}

{% block content %}
<header class="mt-4 mb-3 p-3 pb-5 bg-primary text-white rounded">
    <h1>
        Das ist die Startseite
    </h1>
</header>
{% endblock %}

base/templates/base/imprint.html
{% extends "base/base.html" %}

{% block title %}
Das ist das Impressum dieser Webanwendung
{% endblock %}

{% block meta_description %}
Das ist das Impressum dieser Webanwendung
{% endblock %}

{% block meta_keywords %}
Impressum, Webanwendung
{% endblock %}

{% block content %}
<header class="mt-4 mb-3 p-3 bg-primary text-white rounded">
    <h1>
        Impressum
    </h1>
    <p class="lead text-black">
        Anbieterkennzeichnung gemäß §&nbsp;5&nbsp;TMG
    </p>
</header>
<section>
    <h2>
        Anbieter
    </h2>
    <p>
        {% if provider.IS_BUSINESS and '' != provider.TITLE %}
            {{provider.TITLE}} {{ provider.FIRST_NAME }} {{ provider.LAST_NAME }}<br>
            {{provider.BUSINESS_TYPE}} ({{provider.COMPANY_FORM}})
        {% elif provider.IS_BUSINESS %}
            {{ provider.FIRST_NAME }} {{ provider.LAST_NAME }}<br>
            {{provider.BUSINESS_TYPE}} ({{provider.COMPANY_FORM}})
        {% else %}
        {{ provider.FIRST_NAME }} {{ provider.LAST_NAME }}
        {% endif %}
    </p>
    <p>
        {{provider.STREET}} {{provider.HOUSE_NUMBER}}<br>
        {{provider.POSTCODE}} {{provider.CITY}}<br>
        {{provider.COUNTRY}}
    </p>
    <p>
        {% if '' != provider.PHONE_NUMBER %}
        <b>Telefon: </b>{{provider.PHONE_NUMBER}}<br>
        {% endif %}
        {% if '' != provider.FAX_NUMBER %}
        <b>Fax: </b>{{provider.FAX_NUMBER}}<br>
        {% endif %}
        {% if '' != provider.MOBILE_PHONE_NUMBER %}
        <b>Mobil-Telefon: </b>{{provider.MOBILE_PHONE_NUMBER}}<br>
        {% endif %}
        <b>E-Mail: </b>{{provider.CONTACT_EMAIL}}
    </p>
</section>
{% if '' != provider.TAX_ID_NUMBER %}
<section>
    <h2>
        Umsatzsteuer-ID
    </h2>
    <p>
        Umsatzsteuer-Identifikationsnummer gem&auml;&szlig; &sect;&nbsp;27&nbsp;a&nbsp;Umsatzsteuergesetz:<br>
        {{provider.TAX_ID_NUMBER}}
    </p>
</section>
{% endif %}
<section>
    <h2>
        Verantwortlich f&uuml;r den Inhalt nach &sect;&nbsp;18&nbsp;Abs.&nbsp;2&nbsp;MStV
    </h2>
    <p>
        {% if '' != provider.TITLE %}
        {{provider.TITLE}} {{ provider.FIRST_NAME }} {{ provider.LAST_NAME }} 
        {% else %}
        {{ provider.FIRST_NAME }} {{ provider.LAST_NAME }} 
        {% endif %}
        (Anschrift wie oben)
    </p>
</section>
{% endblock %}

base/templates/base/main_navigation_ bar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        {% if '/' == request.path %} 
        <strong class="navbar-brand" style="font-weight: inherit;">
            My Website
        </strong>
        {% else %}
        <a class="navbar-brand" href="{% url 'base:home' %}">
            My Website
        </a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'base:home' %}">Home</a>
            </div>
        </div>
    </div>
</nav>

base/templates/base/privacy_policy.html
{% extends "base/base.html" %}

{% block title %}
Das sind die Datenschutzrichtlinien dieser Webanwendung
{% endblock %}

{% block meta_description %}
Das sind die Datenschutzrichtlinien dieser Webanwendung
{% endblock %}

{% block meta_keywords %}
Datenschutzrichtlinien, Datenschutz, Webanwendung
{% endblock %}

{% block content %}
<header class="mt-4 mb-3 p-3 pb-5 bg-primary text-white rounded">
    <h1>
        Datenschutzrichtlinien
    </h1>
</header>
{% endblock %}